spring:
  application.name: apigateway

server.port: 8090

zuul:
  routes:
    legacy1:
      path: /api
      url: http://localhost:8080
      sensitive-headers:

security:
  oauth2:    
    client:
      accessTokenUri: http://localhost:7070/uaa/oauth/token
      userAuthorizationUri: http://localhost:7070/uaa/oauth/authorize
      client-id: web_app
      client-secret: secret
    resource:
      userInfoUri: http://localhost:7070/uaa/user
      preferTokenInfo: false     
